site_name: dfipy
site_url: https://dfipy.docs.generalsystem.com/
copyright: Copyright &copy; 2023 - 2024 General System Inc.

theme:
  name: material
  custom_dir: overrides
  logo: assets/general-system-dark.svg
  favicon: assets/favicon.png
  font:
    text: Source Sans Pro
    code: Fira Mono
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # gs-light
      logo: assets/general-system-black.svg
      primary: blue
      accent: orange
      toggle:
        icon: octicons/moon-24
        name: Dark Mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate # gs-dark
      logo: assets/general-system-white.svg
      primary: light blue
      accent: orange
      toggle:
        icon: octicons/sun-24
        name: Light Mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@generalsystem1036
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/thegeneralsystem/about/
    - icon: fontawesome/brands/github
      link: https://github.com/thegeneralsystem
    - icon: general-system/G
      link: https://www.generalsystem.com/

  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: Github
        checked: true
  analytics:
    provider: google
    property: G-YSR9K2NMSD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - privacy
  # - gen-files:
  #     scripts:
  #       - scripts/gen_ref_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            filters: ["!^_"]
            heading_level: 1
            annotations_path: brief
            group_by_category: true
            show_category_heading: false
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_root_toc_entry: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

nav:
  - API Reference:
      - index.md
      - reference/client.md
      - reference/connect.md
      - reference/errors.md
      - reference/validate.md
      - Models:
          - reference/models/query_document.md
          - Filters:
              - Geometry:
                  - reference/models/filters/geometry/bbox.md
                  - reference/models/filters/geometry/point.md
                  - reference/models/filters/geometry/polygon.md
              - reference/models/filters/time_range.md
              - reference/models/filters/filter_fields.md
              - reference/models/filters/only.md
          - Returns:
              - reference/models/returns/count.md
              - reference/models/returns/records.md
      - Services:
          - reference/services/datasets.md
          - reference/services/identities.md
          - reference/services/info.md
          - reference/services/ingest.md
          - reference/services/query.md
          - reference/services/users.md
  - Developer Portal: "https://developers.generalsystem.com/"
